openapi: 3.0.0
info:
  title: User API
  description: API สำหรับจัดการข้อมูลผู้ใช้
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      description: This endpoint creates a new user with a name, email, and password, then returns a JWT token in cookies.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  description: Name of the new user
                  example: John Doe
                email:
                  type: string
                  description: Email of the new user
                  format: email
                  example: johndoe@example.com
                password:
                  type: string
                  description: Password for the new account
                  format: password
                  example: Password123!
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
                  token:
                    type: string
                    description: JWT token for the user
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        "400":
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User already exists
        "500":
          description: Server error during signup
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Error occurred during signup, please try again later
